services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: security-gateway-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.UI
    container_name: security-gateway-ui
    environment:
      - BACKEND_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped